services:
  bot:
    image: mattermost-bot
    depends_on:
      - tarantool
  tarantool:
    image: tarantool/tarantool:latest
    ports:
      - "3301:3301"
networks:
  mm_network:
    external: true
    name: mm_network