services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: 1406
      POSTGRES_DB: mattermost
    volumes:
      - mattermost_db:/var/lib/postgresql/data

  app:
    image: mattermost/mattermost-team-edition
    depends_on:
      - db
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_config:/mattermost/config
      - mattermost_logs:/mattermost/logs
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:1406@db:5432/mattermost?sslmode=disable&connect_timeout=10

volumes:
  mattermost_db:
  mattermost_data:
  mattermost_config:
  mattermost_logs: